---
- name: "bug :bug:"
  color: DA4400
  description: "Something isn't working"

- name: "critical :ambulance:"
  color: FF0000
  description: "Something is broken and needs immidiate attention"

- name: script
  color: 2170FF
  description: "Related to a script"

- name: installer
  color: 000EFF
  description: "Related to the installer script"