---
name: Manage labels

on:
  push:
    paths:
      - ".github/labels.yml"
      - ".github/workflows/manage-labels.yml"

jobs:
  manage-labels:
    name: Update Labels
    uses: CGBassPlayer/sicas-workflows/.github/workflows/manage-labels.yml@main
    with:
      labels_file: .github/labels.yml
      delete_missing: true
